local:  
  database:
    host: "localhost"
    database_port: 5432
    database_name: "postgres"
    user: "postgres"
    password: "123456"  
  server:
    port: 4444
    gracefull_shutdown_timeout: 30